Repository o3de/o3de-extras, pull requests merged in 2023-06, with the labels that each got.

#350 Fix compilation error introduced in #337
  Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.cpp
  Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h
Labels: priority/critical, feature/robotics

#353 Fix `PhysicallyStableClock` crash in MaterialEditor.
  Gems/ROS2/Code/Source/Clock/PhysicallyStableClock.cpp
Labels: kind/bug, feature/robotics

#325 Warehouse Scene Creation Guidelines
  .gitattributes
  Gems/WarehouseAssets/README.md
  Gems/WarehouseAssets/docs/images/WarehouseSceneSampleTree.png
  Gems/WarehouseAssets/docs/images/WarehouseSceneStructure.png
  Templates/Ros2FleetRobotTemplate/docs/images/WarehouseSceneSampleTree.png
  Templates/Ros2FleetRobotTemplate/docs/images/importing_warehousescene_prefab.png
  Templates/Ros2FleetRobotTemplate/docs/images/stacked_warehouses1.png
  Templates/Ros2FleetRobotTemplate/docs/images/stacked_warehouses2.png
  Templates/Ros2FleetRobotTemplate/docs/images/warehouse_assets.png
  Templates/Ros2FleetRobotTemplate/docs/images/warehousescene_prefab.png
  Templates/Ros2FleetRobotTemplate/docs/images/warehousescene_prefab_structure.png
  Templates/Ros2FleetRobotTemplate/docs/scene_creation.md
Labels: kind/enhancement, feature/robotics

#356 compilation fixes and added missing copyrights
  Gems/ROS2/Code/Source/Camera/CameraUtilities.cpp
  Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp
  Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h
  Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.h
  Gems/ROS2/Code/Source/Manipulation/JointMotorControllerComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/JointPublisherComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/ManipulatorControllerComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/PidMotorControllerComponent.cpp
  Gems/ROS2/Code/Source/Utilities/ROS2Conversions.cpp
  Gems/ROS2/Code/Source/VehicleDynamics/Utilities.h
Labels: kind/bug, feature/robotics
