Repository o3de/o3de-extras, pull requests merged in 2023-07, with the labels that each got.

#361 Warehouse Gem: Fixed normal and decal textures
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_blue.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_corner.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_end1.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_end2.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_line.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_mid1.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_mid2.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/tire_traces1.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/tire_traces_circle.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Materials/MWarehouseStorageOnWheels.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseBoxes/WarehouseBoxesNormal.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseFloor/WarehouseFloorNormal.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseGate/WarehouseGateNormal.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseModules/WarehouseModulesNormal.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseProps/WarehousePropsNormal.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseStorage/WarehouseStorageNormal.png.assetinfo
  Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseStorageOnWheels/WarehouseStorageOnWheelsNormal.png.assetinfo
Labels: feature/robotics

#327 Add RobotImporterAPI and behavioral bus
  Gems/ROS2/Code/Include/ROS2/RobotImporter/RobotImporterBus.h
  Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.cpp
  Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp
  Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.h
  Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
  Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.h
  Gems/ROS2/Code/Source/RobotImporter/Utils/FilePath.cpp
  Gems/ROS2/Code/Source/RobotImporter/Utils/FilePath.h
  Gems/ROS2/Code/ros2_editor_files.cmake
Labels: feature/robotics

#378 WarehouseAssets Gem: Shadow bias tuning to prevent artifacts
  Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Components/Ceiling_Lamp.prefab
Labels: feature/robotics

#386 Error messages in Joint Trajectory
  Gems/ROS2/Code/Include/ROS2/Manipulation/JointsTrajectoryRequests.h
  Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.cpp
  Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.h
Labels: kind/feature, sig/simulation, status/backlog, feature/robotics

#393 JointsArticulationController requires ArticulationLink
  Gems/ROS2/Code/Source/Manipulation/Controllers/JointsArticulationControllerComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/Controllers/JointsArticulationControllerComponent.h
Labels: sig/simulation, feature/robotics

#424 Fix missing include in JointsTrajectoryComponent.cpp
  Gems/ROS2/Code/Source/Gripper/GripperActionServer.cpp
  Gems/ROS2/Code/Source/Gripper/GripperActionServerComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp
Labels: kind/bug, feature/robotics

#367 Conveyor belt component.
  Gems/ROS2/Code/CMakeLists.txt
  Gems/ROS2/Code/Include/ROS2/FactorySimulation/ConveyorBeltRequestBus.h
  Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponent.cpp
  Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponent.h
  Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponentConfiguration.cpp
  Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponentConfiguration.h
  Gems/ROS2/Code/Source/ROS2ModuleInterface.h
  Gems/ROS2/Code/ros2_files.cmake
Labels: feature/robotics
