Repository o3de/o3de-extras, pull requests merged in 2023-04, with the labels that each got.

#161 ROS2 Gem: New components for simulating manipulators
  Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameComponent.h
  Gems/ROS2/Code/Include/ROS2/Manipulation/JointPublisherComponent.h
  Gems/ROS2/Code/Include/ROS2/Manipulation/ManipulatorControllerComponent.h
  Gems/ROS2/Code/Include/ROS2/Manipulation/MotorizedJointBus.h
  Gems/ROS2/Code/Include/ROS2/Manipulation/MotorizedJointComponent.h
  Gems/ROS2/Code/Source/Frame/ROS2FrameComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.h
  Gems/ROS2/Code/Source/Manipulation/JointPublisherComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/ManipulatorControllerComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/MotorizedJointComponent.cpp
  Gems/ROS2/Code/Source/ROS2ModuleInterface.h
  Gems/ROS2/Code/Source/ROS2SystemComponent.h
  Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp
  Gems/ROS2/Code/ros2_files.cmake
  Gems/ROS2/Code/ros2_header_files.cmake
  Gems/ROS2/README.md
Labels: feature/robotics

#245 added missing sort header
  Gems/ROS2/Code/Source/Clock/SimulationClock.cpp
  Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp
  Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
Labels: feature/robotics

#224 Warehouse Gem fixes and improvements
  .gitattributes
  Gems/WarehouseAssets/Assets/Prefabs/WarehouseScene.prefab
  Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Storage_on_wheels.prefab
  Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Components/Ceiling_Lamp.prefab
  Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Components/Wall_GI.prefab
  Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Warehouse_Roof.prefab
  Gems/WarehouseAssets/Assets/assets/Materials/storageonwheels.physxmaterial
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_blue.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_corner.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_end1.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_end2.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_line.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_mid1.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_mid2.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/tire_traces1.material
  Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/tire_traces_circle.material
  Gems/WarehouseAssets/Assets/assets/markings_blue.material
  Gems/WarehouseAssets/Assets/assets/markings_blue.png
  Gems/WarehouseAssets/Assets/assets/markings_corner.material
  Gems/WarehouseAssets/Assets/assets/markings_corner.png
  Gems/WarehouseAssets/Assets/assets/markings_end1.material
  Gems/WarehouseAssets/Assets/assets/markings_end1.png
  Gems/WarehouseAssets/Assets/assets/markings_end2.material
  Gems/WarehouseAssets/Assets/assets/markings_end2.png
  Gems/WarehouseAssets/Assets/assets/markings_line.material
  Gems/WarehouseAssets/Assets/assets/markings_line.png
  Gems/WarehouseAssets/Assets/assets/markings_mid1.material
  Gems/WarehouseAssets/Assets/assets/markings_mid1.png
  Gems/WarehouseAssets/Assets/assets/markings_mid2.material
  Gems/WarehouseAssets/Assets/assets/markings_mid2.png
  Gems/WarehouseAssets/Assets/assets/tire_traces1.material
  Gems/WarehouseAssets/Assets/assets/tire_traces1.png
  Gems/WarehouseAssets/Assets/assets/tire_traces_circle.material
  Gems/WarehouseAssets/Assets/assets/tire_traces_circle.png
  Gems/WarehouseAssets/README.md
  Gems/WarehouseAssets/docs/images/CameraSettings.png
  Gems/WarehouseAssets/docs/images/Components.png
  Gems/WarehouseAssets/docs/images/PrefabsFolder.png
  Gems/WarehouseAssets/docs/images/RackProtection.png
  Gems/WarehouseAssets/docs/images/StorageOnWheels.png
  Gems/WarehouseAssets/docs/images/StorageRackPacks.png
  Gems/WarehouseAssets/docs/images/StorageRacks.png
  Gems/WarehouseAssets/docs/images/WarehouseGem.png
  Gems/WarehouseAssets/docs/images/WarehouseScene.png
Labels: feature/robotics

#226 ROS2 URDF importer will parse AMENT_PREFIX_PATH
  Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp
  Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h
  Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
  Gems/ROS2/Code/Tests/UrdfParserTest.cpp
Labels: feature/robotics

#258 Documentation mainpage
  Gems/ROS2/Code/Source/ROS2SystemComponent.h
Labels: kind/documentation, feature/robotics

#267 Ros2ProjectTemplate performance fix
  Gems/WarehouseSample/Assets/O3DEScene/Prefabs/Warehouse.prefab
  Templates/Ros2ProjectTemplate/Template/Levels/DemoLevel/DemoLevel.prefab
Labels: feature/robotics

#244 Camera sensor post processing abstraction
  Gems/ROS2/Code/Include/ROS2/Camera/CameraPostProcessingRequestBus.h
  Gems/ROS2/Code/Source/Camera/CameraSensor.cpp
  Gems/ROS2/Code/Source/Camera/CameraSensor.h
  Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.cpp
  Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.h
  Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp
  Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.h
  Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
  Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.h
  Gems/ROS2/Code/ros2_files.cmake
  Gems/ROS2/Code/ros2_header_files.cmake
Labels: feature/robotics

#243 Adjusted transforms in ROSBot
  Gems/RosRobotSample/Assets/ROSbot.prefab
Labels: feature/robotics

#269 ROS2 Lidar Sensor - fix for incorrect calculation of ray's rotation
  Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp
  Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.cpp
  Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.h
Labels: feature/robotics

#234 Change way of source asset handling in URDF importer
  Gems/ROS2/Code/CMakeLists.txt
  Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp
  Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.h
  Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.cpp
  Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.h
  Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
  Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.h
  Gems/ROS2/Code/Source/RobotImporter/URDF/CollidersMaker.cpp
  Gems/ROS2/Code/Source/RobotImporter/URDF/CollidersMaker.h
  Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp
  Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.h
  Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.cpp
  Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
  Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.h
Labels: feature/robotics

#287 Improve Post Processing Bus
  Gems/ROS2/Code/Include/ROS2/Camera/CameraPostProcessingRequestBus.h
Labels: feature/robotics

#293 Add Proteus Gem description and missing links
  Gems/ProteusRobot/gem.json
  Gems/WarehouseSample/gem.json
Labels: feature/robotics

#292 Add check for prefab creation success
  Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
Labels: feature/robotics

#290 URDF, modify inputbox signals and handling
  Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.cpp
  Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.h
Labels: feature/robotics

#285 Create undo batch for prefab maker
  Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp
Labels: feature/robotics

#298 Add 2D Lidar to RosBot
  Gems/RosRobotSample/Assets/ROSBot_slamtec.prefab
  Gems/RosRobotSample/Assets/ROSbot.prefab
  Gems/RosRobotSample/Assets/ROSbot_velodyne.prefab
  Gems/RosRobotSample/Assets/robot/ros_components_description/meshes/slamtec_rplidar_s1.dae
  Gems/RosRobotSample/Assets/robot/ros_components_description/meshes/slamtec_rplidar_s1_black.material
  Gems/RosRobotSample/Assets/robot/ros_components_description/meshes/slamtec_rplidar_s1_gray.material
  Gems/RosRobotSample/Assets/robot/ros_components_description/meshes/slamtec_rplidar_s1_white.material
  Templates/Ros2ProjectTemplate/Template/Examples/slam_navigation/launch/slam.launch.py
  Templates/Ros2ProjectTemplate/Template/Levels/DemoLevel/DemoLevel.prefab
Labels: feature/robotics

#302 Update autoexec files
  Templates/Ros2FleetRobotTemplate/Template/autoexec.cfg
  Templates/Ros2ProjectTemplate/Template/autoexec.cfg
Labels: feature/robotics

#303 Fixes to Ros2ProjectTemplate, remove unused prefab, fix to non-unity builds
  Gems/ROS2/Assets/Models/Sensors/IMU/AO.png
  Gems/ROS2/Assets/Models/Sensors/IMU/Diffuse.png
  Gems/ROS2/Assets/Models/Sensors/IMU/IMU_MTi10.fbx
  Gems/ROS2/Assets/Models/Sensors/IMU/IMU_MTi10.fbx.assetinfo
  Gems/ROS2/Assets/Models/Sensors/IMU/Normal.png
  Gems/ROS2/Assets/Prefabs/Sensors/Imu.prefab
  Gems/ROS2/Code/Source/Lidar/LidarRegistrarSystemComponent.cpp
  Gems/ROS2/Code/Source/Lidar/LidarRegistrarSystemComponent.h
  Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp
  Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp
  Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.h
  Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
  Templates/Ros2ProjectTemplate/Template/Registry/editorpreferences.setreg
  Templates/Ros2ProjectTemplate/Template/Registry/physxsystemconfiguration.setreg
  Templates/Ros2ProjectTemplate/Template/preview.png
  Templates/Ros2ProjectTemplate/preview.png
  Templates/Ros2ProjectTemplate/template.json
Labels: kind/bug, feature/robotics
