Repository o3de/o3de-extras, pull requests merged in 2024-07, with the labels that each got.

#715 Update ROS 2 sensors base implementation
  Gems/ROS2/Code/Include/ROS2/ROS2SensorTypesIds.h
  Gems/ROS2/Code/Include/ROS2/Sensor/Events/EventSourceAdapter.h
  Gems/ROS2/Code/Include/ROS2/Sensor/ROS2SensorComponentBase.h
  Gems/ROS2/Code/Include/ROS2/Sensor/SensorConfigurationRequestBus.h
  Gems/ROS2/Code/Include/ROS2/Sensor/SensorHelper.h
  Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp
  Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.h
  Gems/ROS2/Code/Source/ContactSensor/ROS2ContactSensorComponent.cpp
  Gems/ROS2/Code/Source/ContactSensor/ROS2ContactSensorComponent.h
  Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.cpp
  Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.h
  Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.cpp
  Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h
  Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp
  Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.h
  Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp
  Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h
  Gems/ROS2/Code/Source/Odometry/ROS2OdometrySensorComponent.cpp
  Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.cpp
  Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.h
  Gems/ROS2/Code/Source/Sensor/SensorHelpers.cpp
  Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.cpp
  Gems/ROS2/Code/ros2_files.cmake
  Gems/ROS2/Code/ros2_header_files.cmake
Labels: sig/simulation, feature/robotics

#718 Fix engine version dependencies for ROS2 and related gems for the o3de stabilization/2409 release
  Gems/ProteusRobot/gem.json
  Gems/ROS2/gem.json
  Gems/RosRobotSample/gem.json
  Gems/WarehouseAutomation/gem.json
  Templates/Ros2FleetRobotTemplate/Template/project.json
  Templates/Ros2FleetRobotTemplate/template.json
  Templates/Ros2ProjectTemplate/Template/project.json
  Templates/Ros2ProjectTemplate/template.json
  Templates/Ros2RoboticManipulationTemplate/Template/project.json
  Templates/Ros2RoboticManipulationTemplate/template.json
  repo.json
Labels: sig/platform, sig/simulation

#724 Lidar: Fixed data acquisition while publishing disabled
  Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp
  Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Labels: sig/simulation

#720 Lidar: Internal storage changed from Euler to quaternion
  Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp
  Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h
  Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.cpp
  Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.h
Labels: sig/simulation

#733 Added support to do MSAA Resolve
  Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp
Labels: sig/graphics-audio, sig/platform

#714 Use simulation time to compute time difference.
  Gems/ROS2/Code/Include/ROS2/Manipulation/MotorizedJoints/JointMotorControllerComponent.h
  Gems/ROS2/Code/Include/ROS2/Utilities/ROS2Conversions.h
  Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.h
  Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp
  Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.h
  Gems/ROS2/Code/Source/Manipulation/MotorizedJoints/JointMotorControllerComponent.cpp
  Gems/ROS2/Code/Source/Utilities/ROS2Conversions.cpp
Labels: sig/simulation

#725 Fix bug in a spawner component
  Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
Labels: sig/simulation

#726 Extend description of frames in o3de
  Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameConfiguration.h
  Gems/ROS2/Code/Source/Frame/ROS2FrameConfiguration.cpp
  Gems/ROS2/Code/Source/Frame/ROS2FrameSystemComponent.h
  Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h
  Gems/ROS2/Code/Source/Lidar/LidarSystem.h
  Gems/ROS2/Code/Source/Sensor/SensorConfiguration.cpp
Labels: sig/simulation

#738 TopicConfiguration: added QoS constructor
  Gems/ROS2/Code/Include/ROS2/Communication/TopicConfiguration.h
Labels: sig/simulation, feature/robotics

#731 [ROS2] Remove deprecated documentation
  Gems/ROS2/docs/design/manipulation/analysis.md
  Gems/ROS2/docs/design/manipulation/architecture.md
  Gems/ROS2/docs/design/manipulation/design.md
  Gems/ROS2/docs/design/manipulation/features.md
  Gems/ROS2/docs/design/manipulation/manipulation.svg
  Gems/ROS2/docs/design/manipulation/manipulation_minimal.svg
  Gems/ROS2/docs/design/manipulation/roadmap.md
  Gems/ROS2/docs/design/vehicle_dynamics/analysis.md
  Gems/ROS2/docs/design/vehicle_dynamics/architecture.md
  Gems/ROS2/docs/design/vehicle_dynamics/design.md
  Gems/ROS2/docs/design/vehicle_dynamics/diagrams/ROSVehicleDynamics_planned.graphml
  Gems/ROS2/docs/design/vehicle_dynamics/diagrams/ROSVehicleDynamics_planned.png
  Gems/ROS2/docs/design/vehicle_dynamics/features.md
  Gems/ROS2/docs/design/vehicle_dynamics/pictures/Ackermann.png
  Gems/ROS2/docs/design/vehicle_dynamics/pictures/DifferentialDrive.png
  Gems/ROS2/docs/design/vehicle_dynamics/pictures/pictures_source_and_licenses.txt
  Gems/ROS2/docs/guides/development_in_clion.md
  Gems/ROS2/docs/guides/pr_publishing.md
  Gems/ROS2/docs/guides/ros2-gem.md
  Gems/ROS2/docs/guides/static/build-config.png
  Gems/ROS2/docs/guides/static/cmake-profile.png
  Gems/ROS2/docs/guides/static/diagrams/diagram_ros2_gem.png
  Gems/ROS2/docs/guides/static/diagrams/diagram_ros2_gem_yEd.graphml
  Gems/ROS2/docs/guides/static/toolchain.png
Labels: priority/minor, sig/simulation
